### PR TITLE
Add netherite tools and weapons support

### PR DESCRIPTION
**Pull request by louisgthier**
Add netherite items check in order for modifiers to work for netherite weapons and tools

### CODE REVIEW

**Comment by NikV2** [comment]
I will, i'll make it more simple though instead of a switch case i'll use the material type endsWith so it'll apply for all tools. Pull Request Closed for now, Commit incoming soon

**Comment by Looowi** [comment]
Could you please separate tools depending on their attack speed of 1.16 ?

**Comment by NikV2** [comment]
What do you mean by seperate?

**Comment by Looowi** [comment]
Allow different modifiers for different materials. For example, in 1.16, hoes have the same damages for each material (1 damage). However, diamond hoe attack speed is 4 times quicker than wooden hoe, making it 4 times better. Adapting damages for each material is then necessary.

**Comment by NikV2** [comment]
If you're talking about specifically goes, cp modifier wont affect hoes since it doesnt count them as tools nor weapons. so their damage wont be affected

**Comment by Looowi** [comment]
They should in fact. Was just going to ask to add them, as at the moment using diamond or wooden hoe doesnt give any avantage. However, i'm also talking about axes. Iron axe has an attack speed of 0.9, diamond/netherite/gold axe of 1, and wooden/gold axe of 0.8

**Comment by NikV2** [comment]
they will be configurable in the next update

**Comment by Looowi** [comment]
Okay thanks this would be awesome. However, cant we just add netherite temporarily as I did before your update ?

**Comment by NikV2** [comment]
i made a commit and a push for it with a simpler way, feel free to compile it. if u cant, let me know so i can provide u with the compiled jar

**Comment by Looowi** [comment]
I cant sorry ^^ It would be really nice if I could get a .jar

**Comment by NikV2** [comment]
https://www.mediafire.com/file/izjs1pimri4hsl7/CombatPlus-1.0.0.jar/file Let me know once u receive it

**Comment by Looowi** [comment]
Could I try adding Hoe support btw ?

**Comment by NikV2** [comment]
doing it right now

**Pull request closed without merging**
